### PR TITLE
Add special cases of param names to ignore

### PR DESCRIPTION
**Pull request by pakelley**
I've been using this package for docstrings lately (thank you for making it, it's very helpful!).
These are a few common cases of params that I don't want to make a docstring for. If you'd prefer, I'd also be happy to make this a customizable variable instead.

### CODE REVIEW

**Comment by douglasdavis** [comment]
This looks like a good addition, thanks for opening a PR! I do think a `defcustom` is a good way to handle it, perhaps `numpydoc-ignored-args`.

**Comment by pakelley** [comment]
Yep, sounds good to me :) I should have time later today or tomorrow to make that change

**Comment by pakelley** [comment]
Should have known better than to give an unsolicited time frame lol. Anyway, finally had a chance to make this customizable (and add some tests & docs).
I also called it `numpydoc-ignored-params` rather than `numpydoc-ignored-args` to better match the "Parameters" section name, but later on saw that you refer to them elsewhere in the code as "args". If you want that changed I can do a quick find/replace, otherwise I think this is ready. :)

**Comment by pakelley** [comment]
Ok I lied, forgot to fix formatting, but NOW it should be ready haha.

**Pull request merged**
